//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets
    {
        public int id { get; set; }
        public int Sum { get; set; }
        public System.DateTime DateOfAdd { get; set; }
    }
}
