//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chaluka
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int SumKerenGive { get; set; }
        public int SumkolelGive { get; set; }
        public int Precent { get; set; }
        public int SumGivePrecent { get; set; }
        public System.DateTime Date { get; set; }
    }
}
