//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kolel()
        {
            this.Persons = new HashSet<Persons>();
        }
    
        public int id { get; set; }
        public string KName { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public int Bank { get; set; }
        public int NumSniff { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime DateOfAdd { get; set; }
        public Nullable<System.DateTime> DateOfDelete { get; set; }
        public int HelpId { get; set; }
        public Nullable<bool> Ok { get; set; }
        public string Style { get; set; }
        public string Space { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<double> CalcBudget { get; set; }
        public int KodMosad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persons> Persons { get; set; }
    }
}
