//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KerenTorahEntities3 : DbContext
    {
        public KerenTorahEntities3()
            : base("name=KerenTorahEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budgets> Budgets { get; set; }
        public virtual DbSet<Chaluka> Chaluka { get; set; }
        public virtual DbSet<Help> Help { get; set; }
        public virtual DbSet<HistoryOutlay> HistoryOutlay { get; set; }
        public virtual DbSet<Instutute> Instutute { get; set; }
        public virtual DbSet<Kolel> Kolel { get; set; }
        public virtual DbSet<Outlay> Outlay { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
    }
}
