//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.HistoryOutlay = new HashSet<HistoryOutlay>();
            this.Outlay = new HashSet<Outlay>();
            this.Outlay1 = new HashSet<Outlay>();
        }
    
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> NumHouse { get; set; }
        public string CellPhone { get; set; }
        public string IdentityOrPassport { get; set; }
        public Nullable<int> Bank { get; set; }
        public Nullable<int> NumSniff { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> Staete { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfAdd { get; set; }
        public Nullable<System.DateTime> DateOfDelete { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOutlay> HistoryOutlay { get; set; }
        public virtual Kolel Kolel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outlay> Outlay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outlay> Outlay1 { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
